### ISSUE TITLE
NullPointerException when visiting AST parsed from empty String

### ISSUE THREAD

**Issue by matheus23** [VerifAPS/iec61131lang#1]
This test case:
```java
package edu.kit.iti.formal.stvs;

import edu.kit.iti.formal.automation.IEC61131Facade;
import edu.kit.iti.formal.automation.visitors.DefaultVisitor;
import org.junit.Test;

public class TestParseEmptyString {

  @Test
  public void testParseEmptyString() {
    IEC61131Facade.file("").visit(new DefaultVisitor<Void>());
  }
}
```
creates a NullPointerException when run:
```
java.lang.NullPointerException
	at edu.kit.iti.formal.automation.st.ast.TopLevelElements.lambda$visit$0(TopLevelElements.java:58)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at edu.kit.iti.formal.automation.st.ast.TopLevelElements.visit(TopLevelElements.java:58)
	at edu.kit.iti.formal.stvs.TestParseEmptyString.testParseEmptyString(TestParseEmptyString.java:14)
```
Am I doing something wrong or is this a bug?

**Comment by wadoon** [comment]
[fixed in version: 0.1.11 ](https://github.com/VerifAPS/iec61131lang/commit/f6304d09f380b439da6a66eb046ae81811518fb1#diff-9140e4c963217333a306e4a071467457R28)
