### ISSUE TITLE
Don't get all allowed values of enum type declaration, only the first.

### ISSUE THREAD

**Issue by matheus23** [VerifAPS/iec61131lang#2]
This test fails on my machine. It seems like the parser doesn't accumulate all possible enum values correctly and just takes the first one it gets:
```java
package edu.kit.iti.formal.stvs;

import edu.kit.iti.formal.automation.IEC61131Facade;
import edu.kit.iti.formal.automation.st.ast.EnumerationTypeDeclaration;
import edu.kit.iti.formal.automation.st.ast.TypeDeclarations;
import edu.kit.iti.formal.automation.visitors.DefaultVisitor;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class TestEnumParse extends DefaultVisitor<Void> {

  String code =
      "TYPE\n" +
      "  MY_ENUM : (one, two, three);\n" +
      "END_TYPE\n";

  @Test
  public void testEnumMembers() {
    IEC61131Facade.file(code).visit(this);
  }

  public Void visit(TypeDeclarations decls) {
    decls.forEach(typeDeclaration -> typeDeclaration.visit(this));
    return null;
  }

  public Void visit(EnumerationTypeDeclaration enumType) {
    System.out.println(enumType.getTypeName());
    System.out.println(enumType.getAllowedValues());
    assertEquals(3, enumType.getAllowedValues().size());
    return null;
  }

}
```
The output is:
```
MY_ENUM
[one]

java.lang.AssertionError: 
Expected :3
Actual   :1
 <Click to see difference>


	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at edu.kit.iti.formal.stvs.TestEnumParse.visit(TestEnumParse.java:35)
	at edu.kit.iti.formal.stvs.TestEnumParse.visit(TestEnumParse.java:14)
	at edu.kit.iti.formal.automation.st.ast.EnumerationTypeDeclaration.visit(EnumerationTypeDeclaration.java:54)
	at edu.kit.iti.formal.stvs.TestEnumParse.lambda$visit$0(TestEnumParse.java:28)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at edu.kit.iti.formal.automation.st.ast.TypeDeclarations.forEach(TypeDeclarations.java:253)
	at edu.kit.iti.formal.stvs.TestEnumParse.visit(TestEnumParse.java:28)
	at edu.kit.iti.formal.stvs.TestEnumParse.visit(TestEnumParse.java:14)
	at edu.kit.iti.formal.automation.st.ast.TypeDeclarations.visit(TypeDeclarations.java:61)
	at edu.kit.iti.formal.automation.st.ast.TopLevelElements.lambda$visit$0(TopLevelElements.java:58)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at edu.kit.iti.formal.automation.st.ast.TopLevelElements.visit(TopLevelElements.java:58)
	at edu.kit.iti.formal.stvs.TestEnumParse.testEnumMembers(TestEnumParse.java:24)
```

This was tested with version 0.1.10.

**Comment by wadoon** [comment]
I fixed it this over christmas, but forgot to upload. [See](https://github.com/VerifAPS/iec61131lang/commit/f6304d09f380b439da6a66eb046ae81811518fb1#diff-9140e4c963217333a306e4a071467457R347)

I have added test case to this project.
